/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package telemetry.test

import java.net.InetSocketAddress
import java.net.Socket
import java.net.SocketAddress
import java.util.Arrays
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val socket = Socket()
        socket.connect(InetSocketAddress("127.0.0.1", 6969))
        val reader = ProtocolReader(BufReader(socket.getInputStream()))
        var i = 0
        while (i < 100000) {
            val payload = reader.nextPayload()
            assert(payload != null)
            println("Got payload: ${Arrays.toString(payload)}")
            i++
        }
    }
}
